### ISSUE TITLE
all parameters shows only RAM, the rest are 0

### ISSUE THREAD

**Issue by openhoangnc** [openhoangnc/taskbar-stats#1]
from @Agafon20's [comment](https://github.com/openhoangnc/taskbar-stats/commit/2ae015a2d9dead47d7ae785dfb8044801a7466a8#commitcomment-43824330)

**Comment by Agafon20** [comment]
![статс](https://user-images.githubusercontent.com/73812670/98457339-aae89380-21b8-11eb-92f0-cd6c23b933fd.jp

**Comment by Agafon20** [comment]
https://yadi.sk/i/ZKFj43-C_q6Ghg

**Comment by Agafon20** [comment]
after installation and adding to the taskbar, only RAM is determined (as you can see in the screenshot), other parameters are not determined!

**Comment by openhoangnc** [comment]
please check Windows's Performance Monitor by run (Windows+R `perfmon`), it should work like this
![image](https://user-images.githubusercontent.com/20717116/98457406-804b0a80-21b9-11eb-8643-a15764e89eae.png)

**Comment by Agafon20** [comment]
https://yadi.sk/i/8X3OML9WxRJYAA

**Comment by openhoangnc** [comment]
please try this https://answers.microsoft.com/en-us/insider/forum/insider_wintp-insider_perf-insiderplat_pc/possible-performance-counter-problem-on-win10/3a5c22cb-1425-4d26-99e7-4ec46940b9a1?auth=1

**Comment by Agafon20** [comment]
https://yadi.sk/i/2ycy6vXSRmeEpw

I did, the rest of the parameters were not activated!  But when changing the language from Russian to English, all the parameters started!  Please tell me, how can I make sure that all the parameters are activated on the Russian layout?

**Comment by openhoangnc** [comment]
currently, all values except ram usage are declared by English, I'm investigating to make it language-independent

**Comment by openhoangnc** [comment]
@Agafon20 please try this version
[TaskbarStats_20.11.8.1_setup.zip](https://github.com/openhoangnc/taskbar-stats/files/5506501/TaskbarStats_20.11.8.1_setup.zip)

**Comment by Agafon20** [comment]
Thank you very much!!!  All parameters were determined with this version! I will definitely follow your further developments!  Thanks!!!
