### ISSUE TITLE
NetSpeed not working on a Bulgarian Win10 1909

### ISSUE THREAD

**Issue by zkvvoob** [openhoangnc/taskbar-stats#11]
Hello,

First of all, thanks for developing Taskbar Stats. I've been looking for an application such as this for quite some time!

I'm not sure whether this has anything to do with the fact that my Windows 10 1909 is using Bulgarian localisation, but while the CPU/RAM meters work fine, the one for NetSpeed do not, even when a YouTube video is running.

How can I help you figure out what's wrong, please?

Thanks.

**Comment by v-zubritsky** [comment]
Same here. Both NetSpeed and NetSpeedBit are showing just zeros, while youtube is open in chrome. 
![image](https://user-images.githubusercontent.com/5411526/108201584-171c5100-7131-11eb-8767-76d466f30cb3.png)

Nothing to do with Bulgarian localization in my case though.

Version in use is 20.11.21.1

**Comment by openhoangnc** [comment]
hello @v-zubritsky please try the pre-release version at https://github.com/openhoangnc/taskbar-stats/releases/tag/v21.3.7.1

**Comment by v-zubritsky** [comment]
@openhoangnc I'm not using your application anymore, so can't provide any help here. Sorry.

**Comment by openhoangnc** [comment]
no more comment, so I close this issue, reopen if you need
