### ISSUE TITLE
[Feature] Percentage for RAM

### ISSUE THREAD

**Issue by UsamaKarim** [openhoangnc/taskbar-stats#12]
Thanks for making it available for free 💕
Can you please add the percentage option/default for RAM? I think it suits more because the CPU has a percentage style too, and the percentage provide faster information than the value. I hope you understand what I mean.

**Comment by openhoangnc** [comment]
hi @UsamaKarim 
I added percentage for RAM, please check at https://github.com/openhoangnc/taskbar-stats/releases
![image](https://user-images.githubusercontent.com/20717116/113477317-24a45500-94ab-11eb-881f-7c5af4c80bb5.png)

Please consider making a donation to help me maintain this software.
<a href="https://www.buymeacoffee.com/hoangnc"><img src="https://img.buymeacoffee.com/button-api/?text=Buy me a rice bowl&emoji=🍚&slug=hoangnc&button_colour=40DCA5&font_colour=ffffff&font_family=Comic&outline_colour=000000&coffee_colour=FFDD00"></a>
