### ISSUE TITLE
Display too tiny on a UHD screen

### ISSUE THREAD

**Issue by gs-gaurav** [openhoangnc/taskbar-stats#13]
This is one of the applications I can't live without. Recently I bought a laptop with UHD screen and now its hard for me to see Taskbar Stats on the taskbar. Please update so the font display size either automatically adjust or there is option to control the font size.
![Screenshot 2021-03-13 115332](https://user-images.githubusercontent.com/80397191/111021493-c4ae1780-83f2-11eb-96c9-1f518ee64a2a.png)

**Comment by ztalk112** [comment]
Same for me. Screen rez 3000 x 2000.

**Comment by openhoangnc** [comment]
hi @gs-gaurav @ztalk112 
I updated the font display size automatically adjust,  please check at https://github.com/openhoangnc/taskbar-stats/releases

![image](https://user-images.githubusercontent.com/20717116/113477543-b1034780-94ac-11eb-88a5-baeb9b2ae4ca.png)



Please consider making a donation to help me maintain this software.
<a href="https://www.buymeacoffee.com/hoangnc"><img src="https://img.buymeacoffee.com/button-api/?text=Buy me a rice bowl&emoji=🍚&slug=hoangnc&button_colour=40DCA5&font_colour=ffffff&font_family=Comic&outline_colour=000000&coffee_colour=FFDD00"></a>

**Comment by ztalk112** [comment]
Hi there,

Thanks for the update!

The increased font size on my high-resolution monitor works well. I also
like that you changed the RAM display to percentage.

Remaining issues/requests:

1. The CPU+RAM stats do not display!
The other three display correctly. However, CPU+RAM are actually the only
stats that I want.

2. Please add an option to start the app on Windows startup (and reboot).

Fix these two things and I will make a donation :)

Thanks,
Gary

**Comment by openhoangnc** [comment]
hi @ztalk112 

About your remaining issues:
1. If it do not display, nothing I can do, you may need to remove and reinstall
2. Once you select to display, it should display on Windows startup, no addition option needed

I close this issue, create an other if you need.
