### ISSUE TITLE
Font size too large in the vertical taskbars

### ISSUE THREAD

**Issue by frautschmied** [openhoangnc/taskbar-stats#16]
Seems to be introduced by the fix of #13
Is it possible to detect the position of taskbar?
![image](https://user-images.githubusercontent.com/46593445/115383247-2a6a9c00-a208-11eb-8be6-78c79d9420a6.png)
Many thanks

**Comment by openhoangnc** [comment]
there, I fixed it [v21.4.21.1](https://github.com/openhoangnc/taskbar-stats/releases/tag/v21.4.21.1)
![image](https://user-images.githubusercontent.com/20717116/115492903-eb325e80-a28c-11eb-89e4-7d6740ee459e.png)

<a href="https://www.buymeacoffee.com/hoangnc"><img src="https://img.buymeacoffee.com/button-api/?text=Buy me a rice bowl&emoji=🍚&slug=hoangnc&button_colour=40DCA5&font_colour=ffffff&font_family=Comic&outline_colour=000000&coffee_colour=FFDD00"></a>
