### ISSUE TITLE
Toolbar Location includes unwanted space 

### ISSUE THREAD

**Issue by Atif-Anwer** [openhoangnc/taskbar-stats#17]
![image](https://user-images.githubusercontent.com/28299708/116957182-8406a800-ac97-11eb-9e0b-03a873d0c29d.png)

The position of the toolbar is overlapped with other toolbars, and includes uneditable blank spaces. 
Currently using 'Small Taskbar Icons' setting.. Would be great if the location can be fixed or edited.

**Comment by openhoangnc** [comment]
please include some more pictures of:
- only batteryBar
- only taskbar-stats

**Comment by Atif-Anwer** [comment]
Well, it was not Taskbar afterall. I tried playing around with options etc and figured somehow the Windows News widget was enabled by M$ Edge after updates. And it does not support the taskbar when it is located anywhere other than the bottom of the screen ( i have the taskbar at the top). So closing the issue. Thanks!
