### ISSUE TITLE
Feature request: show units as bits instead of bytes

### ISSUE THREAD

**Issue by gcwill70** [openhoangnc/taskbar-stats#2]
Create an option to change units between Byte/Kilobyte/Megabyte/... and Bit/Kilobit/Megabit/...

Would be nice to have because network speeds are typically measured in Mbps/Kbps/bps instead of MBps/KBps/Bps

**Comment by openhoangnc** [comment]
good suggestion, will have another option in toolbars to display network speed as (x)bps

**Comment by openhoangnc** [comment]
@gcwill70 please check the latest version https://github.com/openhoangnc/taskbar-stats/releases/tag/v20.11.21.1

**Comment by gcwill70** [comment]
Works great! Thank you! Now my speeds will match speedtest.net :)
