### ISSUE TITLE
How to uninstall

### ISSUE THREAD

**Issue by FelipeGlauber** [openhoangnc/taskbar-stats#20]
Please, add an option to uninstall

**Comment by openhoangnc** [comment]
Check this
https://support.microsoft.com/en-us/windows/uninstall-or-remove-apps-and-programs-in-windows-10-4b55f974-2cc6-2d2b-d092-5905080eaf98

**Comment by FelipeGlauber** [comment]
> Check this https://support.microsoft.com/en-us/windows/uninstall-or-remove-apps-and-programs-in-windows-10-4b55f974-2cc6-2d2b-d092-5905080eaf98

It was useless. But I found a useful support at this site by pointing the correct uninstall folder. Software was not listed under Control Panel.
https://www.advanceduninstaller.com/Taskbar-stats-version-20_2_14_1-7fc2a5cea7f74da2bdd992761c6221cf-application.htm

Thank you, anyway
