### ISSUE TITLE
Enhancement Idea: Open Task Manager on (double) click

### ISSUE THREAD

**Issue by suuppl** [openhoangnc/taskbar-stats#22]
Hi, so far I really like taskbar-stats 😄. I tried a few similar projects, but that one is the best yet.
Another one (XMeters, the copyright notice on their website is from 2017...) could open the task manager when clicking on any of the stats. I think that would be nice for taskbar-stats as well.
Maybe you could add an option in the right-click menu to make it optional?

**Comment by openhoangnc** [comment]
Instead of right click in taskbar-stats, right click on blank area in the taskbar.
![image](https://user-images.githubusercontent.com/20717116/119767347-da56b780-bee0-11eb-82d2-f6ae5f1a250c.png)
It's ok to double click to open task manager, but personally I don't need this feature.

**Comment by suuppl** [comment]
Usually I open the task manager via Ctrl+Shift+Esc, just liked this particular feature of XMeters, but you decide ;) Thank you!
