### ISSUE TITLE
[Request] Publish source code

### ISSUE THREAD

**Issue by suuppl** [openhoangnc/taskbar-stats#24]
Hi again ;)

Did you come to a conclusion about open sourcing your code?
I think it would be really nice to allow others to work on this project as it has a few open issues and quite a few stars.
You could give it a license like CC-BY-NC-ND or CC-BY-ND if you don't want any derivatives (Also check out this [license selector](http://ufal.github.io/public-license-selector/). You can either click through the selector or just search for licenses).

Ultimately, you decide of course. If you don't want to publish your code that's fine as well.

Thanks! 😄

**Comment by chneau** [comment]
Hello, @suuppl

This project looks to be closely related to https://github.com/AzureGreen/NetView which is MIT.

**Comment by openhoangnc** [comment]
hi @chneau I have no intent to open source at this moment.
