### ISSUE TITLE
VirusTotal flags latest release as malicious

### ISSUE THREAD

**Issue by valpamp** [openhoangnc/taskbar-stats#26]
3/69 security vendors flag the latest release exe as malicious, here's the [link](https://www.virustotal.com/gui/file/7eb02c48277be2a5838a532bfde20eca87cb4ba7c182acfddafae2eab3512ec1/detection).
![Screen](https://user-images.githubusercontent.com/50947671/121775465-2d3e9900-cb88-11eb-975b-9f8d37f82721.png)

**Comment by limonkufu** [comment]
Seeing that none of the source folders are changed but the latest release includes some fixes that do not map to the source code, I suspect that the exe is not generated from the source code here so I would be very suspicious about it until it's cleared.

**Comment by openhoangnc** [comment]
hello limonkufu, this software is not open source, [privacy policy here](https://github.com/openhoangnc/taskbar-stats/blob/master/Privacy-policy.md)

hello valpamp, I can only say "false positive" #4

anyway, use at your own risk

**Comment by limonkufu** [comment]
@openhoangnc hi, sorry I didn't realise it, should've looked better. Please accept my apologies
