### ISSUE TITLE
[Request] Add support for Win11

### ISSUE THREAD

**Issue by hikariatama** [openhoangnc/taskbar-stats#27]
I have Win11, and there is no "Panels" option in taskbar settings.
![изображение](https://user-images.githubusercontent.com/36935426/126135886-75a94c7b-062b-4020-9222-9a3824be13f8.png)
In Settings there is also nothing.
![изображение](https://user-images.githubusercontent.com/36935426/126135951-a72b766d-9b53-4b92-8858-de50f68b235d.png)
Please, add support for this OC

**Comment by owainharris** [comment]
+1

**Comment by tripplehelix** [comment]
+2

**Comment by tripplehelix** [comment]
You can get this working by using https://www.startallback.com/

![image](https://user-images.githubusercontent.com/16861223/136212828-2e148873-c29c-4eb3-a07b-75485d58d0cb.png)

**Comment by 3lsheikh** [comment]
+1

**Comment by openhoangnc** [comment]
Thank you all for your comments.
I'm working on #31 .
