### ISSUE TITLE
Network stats not showing

### ISSUE THREAD

**Issue by alabliuk** [openhoangnc/taskbar-stats#3]
Hi,

My network statistics are 0, is there a configuration file that can change the network interface?

![Screenshot 2020-11-14 235952](https://user-images.githubusercontent.com/26491463/99161919-1f9a6100-26d6-11eb-8093-23db96626133.jpg)

**Comment by openhoangnc** [comment]
network interfaces are detected automatically, this is a bug, I'm investigating it

**Comment by openhoangnc** [comment]
hi @alabliuk, please try this console program [NetSpeedConsole.zip](https://github.com/openhoangnc/taskbar-stats/files/5542517/NetSpeedConsole.zip)
you will see output like this
![image](https://user-images.githubusercontent.com/20717116/99187559-e0c5e300-2789-11eb-885c-e1bb437d097c.png)
If your "Up and Down" values are not zero, I will release a new version to fix the bug soon, otherwise, error detail should be shown on screen, please capture it and send me.

**Comment by alabliuk** [comment]
I think there was some dll missing in the package, this is giving error:

![image](https://user-images.githubusercontent.com/26491463/99191664-d9ccaf80-274c-11eb-8e19-2935cceeaed4.png)

![image](https://user-images.githubusercontent.com/26491463/99191671-e4874480-274c-11eb-8ca2-793e61012a6c.png)

![image](https://user-images.githubusercontent.com/26491463/99191680-efda7000-274c-11eb-9af9-3818d4e645a2.png)

![image](https://user-images.githubusercontent.com/26491463/99191685-f668e780-274c-11eb-9fb3-73e3cb399eef.png)

![image](https://user-images.githubusercontent.com/26491463/99191695-0f719880-274d-11eb-9476-74cf9497f2f9.png)

**Comment by alabliuk** [comment]
I don't know if this could be a problem, but I use a Network Bridge because of Hyper-V

![image](https://user-images.githubusercontent.com/26491463/99191808-f9b0a300-274d-11eb-8a59-efeb3339b59c.png)

**Comment by openhoangnc** [comment]
please try download an install "Visual C++ Redistributable for Visual Studio 2015"
 https://www.microsoft.com/en-US/download/details.aspx?id=48145
then run the program again

**Comment by alabliuk** [comment]
Strange because I already have this package installed

![image](https://user-images.githubusercontent.com/26491463/99209728-9735c200-27a2-11eb-966f-7c056991cad3.png)

**Comment by openhoangnc** [comment]
please try again with this program [NetSpeedConsole.zip](https://github.com/openhoangnc/taskbar-stats/files/5547437/NetSpeedConsole.zip)



> I don't know if this could be a problem, but I use a Network Bridge because of Hyper-V
> 
> ![image](https://user-images.githubusercontent.com/26491463/99191808-f9b0a300-274d-11eb-8a59-efeb3339b59c.png)
Virtual network interfaces would not be counted, should have no problem here.

**Comment by alabliuk** [comment]
@openhoangnc 

![image](https://user-images.githubusercontent.com/26491463/99293050-dacf1100-2820-11eb-8de7-6206491218fe.png)

**Comment by Tsiikki** [comment]
Hello!

I have this same problem. Win10 Pro 1909 Finnish language.
![image](https://user-images.githubusercontent.com/74696671/99620861-117a7680-2a2f-11eb-90ee-0d39b218f739.png)

**Comment by ANIKET-DALAL** [comment]
@openhoangnc 
[NetSpeedConsole.zip](https://github.com/openhoangnc/taskbar-stats/files/5567087/NetSpeedConsole.zip) 
NetSpeedConsole.exe is not getting installed it is showing various .dll files missing.


![image](https://user-images.githubusercontent.com/57136186/99674065-8c797680-2a9b-11eb-9f8a-96241ecbbe51.png)
![image](https://user-images.githubusercontent.com/57136186/99674084-9307ee00-2a9b-11eb-9b20-11380c193114.png)
![image](https://user-images.githubusercontent.com/57136186/99674108-98fdcf00-2a9b-11eb-8f11-88e990d1288d.png)
![image](https://user-images.githubusercontent.com/57136186/99674122-9f8c4680-2a9b-11eb-870a-69bd9ee5487b.png)

**Comment by openhoangnc** [comment]
Hi everyone, I'm continuing to investigate this problem, please wait

@ANIKET-DALAL 
> please try again with this program [NetSpeedConsole.zip](https://github.com/openhoangnc/taskbar-stats/files/5547437/NetSpeedConsole.zip)

@alabliuk I see there are no network interfaces listed in the console

@Tsiikki seem it related to Windows language

**Comment by alabliuk** [comment]
@openhoangnc I did a new test ... I removed the network configuration of the hypev (virtual switch hyper-v) and the network bridge.

And after these steps I was able to see my network interfaces in NetSpeedConsole and the network rates started to be displayed.

![image](https://user-images.githubusercontent.com/26491463/99870819-ba9ea980-2bb4-11eb-8ec5-f8adc343a2b9.png)

![image](https://user-images.githubusercontent.com/26491463/99870842-dc982c00-2bb4-11eb-9681-f1d5a928d437.png)

Unfortunately when I recreated the network settings the interfaces disappeared from NetSpeedConsole

![image](https://user-images.githubusercontent.com/26491463/99870959-a7d8a480-2bb5-11eb-92f3-e5ac637f7a79.png)

I think hyper v should change some interface configuration when configured ... I will do some other tests to get more information.

**Comment by openhoangnc** [comment]
hi everyone, please test this console program, it should work now (I hope that)
[NetSpeedConsole.zip](https://github.com/openhoangnc/taskbar-stats/files/5577376/NetSpeedConsole.zip)

**Comment by ANIKET-DALAL** [comment]
hi @openhoangnc [NetSpeedConsole.zip](https://github.com/openhoangnc/taskbar-stats/files/5577492/NetSpeedConsole.zip)
is working now.
![image](https://user-images.githubusercontent.com/57136186/99875822-7fce5d00-2c18-11eb-8e33-a94de346d3a6.png)

but still its zero at taskbar after re-installing
![image](https://user-images.githubusercontent.com/57136186/99875844-a2f90c80-2c18-11eb-8b34-515de1a15eb8.png)

**Comment by openhoangnc** [comment]
hi @ANIKET-DALAL please install the newest version https://github.com/openhoangnc/taskbar-stats/releases/tag/v20.11.21.1

**Comment by ANIKET-DALAL** [comment]
@openhoangnc file is asking for password

**Comment by openhoangnc** [comment]
> @openhoangnc file is asking for password

oh, sorry, just re-uploaded, please download again

**Comment by alabliuk** [comment]
This new version is works.

![image](https://user-images.githubusercontent.com/26491463/99882574-412ca880-2c00-11eb-9875-09f808db49d6.png)

![image](https://user-images.githubusercontent.com/26491463/99882581-48ec4d00-2c00-11eb-9f47-5b7c64a39135.png)

Good job!
