### ISSUE TITLE
Virustotal shows malware detections on release file

### ISSUE THREAD

**Issue by scottchamings** [openhoangnc/taskbar-stats#4]
The release file TaskbarStats_20.11.8.1_setup.exe is showing with malware detections at VirusTotal as per 
https://www.virustotal.com/gui/file/0c88703b84500a850dfbeb47763922053e04d69e97fe30335bb2e9ecfb9846dd/detection

**Comment by openhoangnc** [comment]
hi @scottchamings 
I believe these detections are false positive, maybe cause by [Inno setup](https://jrsoftware.org/isinfo.php)
If you still worry about virus, just do not use it.
If you want to use, just install and enjoy.

**Comment by openhoangnc** [comment]
I have reported false positive to those antivirus software companies,
for now, nothing to do more, so I close this issue
