### ISSUE TITLE
Awesome work but..

### ISSUE THREAD

**Issue by Marvinoo** [openhoangnc/taskbar-stats#5]
Please add some options/configs to customize some elements like the Font family, Font size, colors.. because the default font is kinda big and distracting. Thank you so much.

**Comment by openhoangnc** [comment]
Hi @Marvinoo, thank you for your suggestion.
currently, I use a fixed-width font to keep the icons and units fixed position, yes it is big if you compare with the date-time in the corner, but actually it almost the same height as the date-times font, some characters even smaller (the M character in the picture below)
![image](https://user-images.githubusercontent.com/20717116/99901021-259bcd80-2ce6-11eb-8272-a765e7e3b432.png)
Btw, I think your suggestion is good, will be useful for someone who loves customization like you.
But, you know, this is free software, I can not spend much time on it.

**Comment by Marvinoo** [comment]
Aha ok. I'll use it as it is even if it would take sometimes to get used to the look of it. Thanks anyway mate. Cheers
