### ISSUE TITLE
Windows Defender flagging as malware

### ISSUE THREAD

**Issue by stunlocked94** [openhoangnc/taskbar-stats#6]
After downloading this tool Windows Defender alerted me of a malware issue and deleted the file.

The link given by Defender: https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=Trojan%3aScript%2fOneeva.A!ml&threatid=2147729349

**Comment by openhoangnc** [comment]
you have 2 options:
- take no action and forget this software, there are some alternatives such
as xmeter https://entropy6.com/xmeters/
- turn off Windows Defender, download and install this software, then turn
on Windows Defender again

**Comment by xmha97** [comment]
Windows Defender deleted the ZIP file but not the EXE file!
![Windows Defender](https://user-images.githubusercontent.com/23485114/100915981-5f40b580-34ea-11eb-8144-389771eea65a.png)
Please release the setup file as an EXE file.
Thanks.

**Comment by mntorq** [comment]
I go the same thing.  
![image](https://user-images.githubusercontent.com/66257685/100963420-4b9a4c80-34f4-11eb-8026-322272633790.png)

**Comment by xmha97** [comment]
> I got the same thing.
> ![image](https://user-images.githubusercontent.com/66257685/100963420-4b9a4c80-34f4-11eb-8026-322272633790.png)

Disable Windows Defender
Unzip Downloaded file
Enable Windows Defender
Install the app.
Windows Defender deleted the ZIP file but not the EXE file!

**Comment by mntorq** [comment]
Yeah, I'm definitely not doing that.  False positives are extremely rare with Defender.  Rather the author get it clean.

**Comment by openhoangnc** [comment]
I uploaded exe file
