### ISSUE TITLE
Disk & network stats broken after Win10 20H2

### ISSUE THREAD

**Issue by mntorq** [openhoangnc/taskbar-stats#7]
Disk & network stats broken after Win10 20H2
They show 0.

**Comment by xmha97** [comment]
I'm using Windows 10 20H2 and all the TaskbarStats toolbars are working properly on my system. 👍 
![Windows 10 Taskbar](https://user-images.githubusercontent.com/23485114/100945591-c5433200-3516-11eb-8afa-c1683905ae38.png)

**Comment by mntorq** [comment]
Hmm, Well, mine are dead and it only started after that installation.  I suppose uninstall/reinstall?

**Comment by xmha97** [comment]
I installed TaskbarStats for the first time since Windows upgrade.

**Comment by alboo89** [comment]
me too, with the last versione 20H2  cpu and disk are not working .
![image](https://user-images.githubusercontent.com/49145474/101535129-76731d80-3998-11eb-95d7-240a58481bd2.png)
they never worked since it's a fresh first time install. 
CPU is an amd ryzen 5 2500

**Comment by gianvi97** [comment]
The same here with Windows 1809

**Comment by openhoangnc** [comment]
hi, I attached a console program for debugging, please run and send me your console log.
[NetSpeedConsoleBit.zip](https://github.com/openhoangnc/taskbar-stats/files/5744577/NetSpeedConsoleBit.zip)

**Comment by xantilon** [comment]
NetSpeedConcoleBit shows only 
Up      0  | Down    0

20H2 (Build 19042.746)

**Comment by SergeantSerk** [comment]
Same as others, just after installation it was showing successfully and then it is constant 0 for download and upload. Windows 10 20H2, this is before restart.

**Comment by openhoangnc** [comment]
hi @xantilon 
I attach new program including more debug information and some trying to fix, please test

[NetSpeedConsoleBit.zip](https://github.com/openhoangnc/taskbar-stats/files/6096828/NetSpeedConsoleBit.zip)

**Comment by openhoangnc** [comment]
no more comment, so I close this issue, reopen if you need
